/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'publishedAt' : Time,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
});
export const BreakingNews = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'text' : IDL.Text,
});
export const LocalNewsArticle = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'publishedAt' : Time,
  'sourceUrl' : IDL.Text,
  'sourceName' : IDL.Text,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'imageBase64' : IDL.Text,
  'category' : IDL.Text,
});
export const ExternalNews = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'fetchedAt' : Time,
  'sourceUrl' : IDL.Text,
  'sourceName' : IDL.Text,
  'summary' : IDL.Text,
  'category' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpResponse = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformArgs = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpResponse,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'addLocalNews' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createBreakingNews' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteLocalNews' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'fetchExternalNews' : IDL.Func([], [IDL.Nat], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllBreakingNews' : IDL.Func([], [IDL.Vec(BreakingNews)], ['query']),
  'getAllLocalNews' : IDL.Func([], [IDL.Vec(LocalNewsArticle)], ['query']),
  'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getExternalNews' : IDL.Func([], [IDL.Vec(ExternalNews)], ['query']),
  'getFeaturedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getLastFetchedTime' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getLocalNewsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(LocalNewsArticle)],
      ['query'],
    ),
  'searchLocalNews' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LocalNewsArticle)],
      ['query'],
    ),
  'transform' : IDL.Func([TransformArgs], [HttpResponse], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'publishedAt' : Time,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
  });
  const BreakingNews = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'text' : IDL.Text,
  });
  const LocalNewsArticle = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'publishedAt' : Time,
    'sourceUrl' : IDL.Text,
    'sourceName' : IDL.Text,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'imageBase64' : IDL.Text,
    'category' : IDL.Text,
  });
  const ExternalNews = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'fetchedAt' : Time,
    'sourceUrl' : IDL.Text,
    'sourceName' : IDL.Text,
    'summary' : IDL.Text,
    'category' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpResponse = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformArgs = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpResponse,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'addLocalNews' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createBreakingNews' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteLocalNews' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'fetchExternalNews' : IDL.Func([], [IDL.Nat], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllBreakingNews' : IDL.Func([], [IDL.Vec(BreakingNews)], ['query']),
    'getAllLocalNews' : IDL.Func([], [IDL.Vec(LocalNewsArticle)], ['query']),
    'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getExternalNews' : IDL.Func([], [IDL.Vec(ExternalNews)], ['query']),
    'getFeaturedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getLastFetchedTime' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getLocalNewsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(LocalNewsArticle)],
        ['query'],
      ),
    'searchLocalNews' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LocalNewsArticle)],
        ['query'],
      ),
    'transform' : IDL.Func([TransformArgs], [HttpResponse], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };