/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'publishedAt' : Time,
  'author' : string,
  'summary' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
}
export interface BreakingNews {
  'id' : bigint,
  'createdAt' : Time,
  'text' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'createArticle' : ActorMethod<
    [string, string, string, string, string, boolean],
    bigint
  >,
  'createBreakingNews' : ActorMethod<[string], bigint>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllBreakingNews' : ActorMethod<[], Array<BreakingNews>>,
  'getArticle' : ActorMethod<[bigint], Article>,
  'getFeaturedArticles' : ActorMethod<[], Array<Article>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];