/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'publishedAt' : Time,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
});
export const BreakingNews = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'text' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'createArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createBreakingNews' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllBreakingNews' : IDL.Func([], [IDL.Vec(BreakingNews)], ['query']),
  'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getFeaturedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'publishedAt' : Time,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
  });
  const BreakingNews = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'text' : IDL.Text,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'createArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createBreakingNews' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllBreakingNews' : IDL.Func([], [IDL.Vec(BreakingNews)], ['query']),
    'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getFeaturedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };