/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'publishedAt' : Time,
  'author' : string,
  'summary' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
}
export interface BreakingNews {
  'id' : bigint,
  'createdAt' : Time,
  'text' : string,
}
export interface ExternalNews {
  'id' : bigint,
  'title' : string,
  'fetchedAt' : Time,
  'sourceUrl' : string,
  'sourceName' : string,
  'summary' : string,
  'category' : string,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpResponse {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface LocalNewsArticle {
  'id' : bigint,
  'title' : string,
  'publishedAt' : Time,
  'sourceUrl' : string,
  'sourceName' : string,
  'author' : string,
  'summary' : string,
  'imageBase64' : string,
  'category' : string,
}
export type Time = bigint;
export interface TransformArgs {
  'context' : Uint8Array,
  'response' : HttpResponse,
}
export interface _SERVICE {
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'addLocalNews' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'createArticle' : ActorMethod<
    [string, string, string, string, string, boolean],
    bigint
  >,
  'createBreakingNews' : ActorMethod<[string], bigint>,
  'deleteLocalNews' : ActorMethod<[bigint], boolean>,
  'fetchExternalNews' : ActorMethod<[], bigint>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllBreakingNews' : ActorMethod<[], Array<BreakingNews>>,
  'getAllLocalNews' : ActorMethod<[], Array<LocalNewsArticle>>,
  'getArticle' : ActorMethod<[bigint], Article>,
  'getExternalNews' : ActorMethod<[], Array<ExternalNews>>,
  'getFeaturedArticles' : ActorMethod<[], Array<Article>>,
  'getLastFetchedTime' : ActorMethod<[], [] | [Time]>,
  'getLocalNewsByDateRange' : ActorMethod<
    [Time, Time],
    Array<LocalNewsArticle>
  >,
  'searchLocalNews' : ActorMethod<[string], Array<LocalNewsArticle>>,
  'transform' : ActorMethod<[TransformArgs], HttpResponse>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];