/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Article {
    id: bigint;
    title: string;
    publishedAt: Time;
    author: string;
    summary: string;
    imageUrl: string;
    isFeatured: boolean;
    category: string;
}
export type Time = bigint;
export interface BreakingNews {
    id: bigint;
    createdAt: Time;
    text: string;
}
export interface LocalNewsArticle {
    id: bigint;
    title: string;
    publishedAt: Time;
    sourceUrl: string;
    sourceName: string;
    author: string;
    summary: string;
    imageBase64: string;
    category: string;
}
export interface ExternalNews {
    id: bigint;
    title: string;
    fetchedAt: Time;
    sourceUrl: string;
    sourceName: string;
    summary: string;
    category: string;
}
export interface HttpResponse {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface TransformArgs {
    context: Uint8Array;
    response: HttpResponse;
}
export interface backendInterface {
    addAdmin(admin: Principal): Promise<void>;
    addLocalNews(title: string, summary: string, category: string, imageBase64: string, author: string, sourceName: string, sourceUrl: string): Promise<bigint>;
    createArticle(title: string, summary: string, category: string, imageUrl: string, author: string, isFeatured: boolean): Promise<bigint>;
    createBreakingNews(text: string): Promise<bigint>;
    deleteLocalNews(id: bigint): Promise<boolean>;
    fetchExternalNews(): Promise<bigint>;
    getAllArticles(): Promise<Array<Article>>;
    getAllBreakingNews(): Promise<Array<BreakingNews>>;
    getAllLocalNews(): Promise<Array<LocalNewsArticle>>;
    getArticle(id: bigint): Promise<Article>;
    getExternalNews(): Promise<Array<ExternalNews>>;
    getFeaturedArticles(): Promise<Array<Article>>;
    getLastFetchedTime(): Promise<Time | null>;
    getLocalNewsByDateRange(fromTimestamp: Time, toTimestamp: Time): Promise<Array<LocalNewsArticle>>;
    searchLocalNews(keyword: string): Promise<Array<LocalNewsArticle>>;
    transform(args: TransformArgs): Promise<HttpResponse>;
}
import type { Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return result;
        }
    }
    async addLocalNews(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLocalNews(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLocalNews(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createArticle(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createBreakingNews(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBreakingNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBreakingNews(arg0);
            return result;
        }
    }
    async deleteLocalNews(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLocalNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLocalNews(arg0);
            return result;
        }
    }
    async fetchExternalNews(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchExternalNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchExternalNews();
            return result;
        }
    }
    async getAllArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArticles();
            return result;
        }
    }
    async getAllBreakingNews(): Promise<Array<BreakingNews>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBreakingNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBreakingNews();
            return result;
        }
    }
    async getAllLocalNews(): Promise<Array<LocalNewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLocalNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLocalNews();
            return result;
        }
    }
    async getArticle(arg0: bigint): Promise<Article> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return result;
        }
    }
    async getExternalNews(): Promise<Array<ExternalNews>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExternalNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExternalNews();
            return result;
        }
    }
    async getFeaturedArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedArticles();
            return result;
        }
    }
    async getLastFetchedTime(): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastFetchedTime();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastFetchedTime();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocalNewsByDateRange(arg0: Time, arg1: Time): Promise<Array<LocalNewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocalNewsByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocalNewsByDateRange(arg0, arg1);
            return result;
        }
    }
    async searchLocalNews(arg0: string): Promise<Array<LocalNewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchLocalNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchLocalNews(arg0);
            return result;
        }
    }
    async transform(arg0: TransformArgs): Promise<HttpResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
